### ISSUE TITLE
Changer checklist

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/license-changer#1]
## Checklist for license changer QA:
- ``git grep -i "GPL"``
- ``git grep -i "pypy"``
- Non-Invenio packages (e.g. "dcxml"), should not have "Invenio" in the license headers and probably nowhere in the code anywhere: ``git grep -i Invenio``
- Review the list of authors in AUTHORS.rst. Should be no duplicate names.
- Check if README.rst has updated version tag badge and that the Image (shield.io) and the URL resolve to PyPy package repo
- All commits should be made by ```"Invenio <info@inveniosoftware.org>"```

**Comment by krzysztof** [comment]
### License changes should be done incognito:

First, check what your current settings are:
```git config --global user.name```
```git config --global user.email```

store it and then change it to
```git config --global user.name "Invenio"```
```git config --global user.email "info@inveniosoftware.org"```

**Comment by switowski** [comment]
- [ ] `AUTHORS.rst`:
  * [ ] Check if the list of contributors in was changed (No duplicates? No *weird* names?)
  * [ ] Check if there is license on top of the file
- [ ] Check if `.travis.yml` has:
  * [ ] `allow_failures` specifying tests that are using `env: REQUIREMENTS=devel ...`
  * [ ] username for pypi: `inveniosoftware`
  * [ ] changed password for pypi

**Comment by krzysztof** [comment]
Repositories which require manual version bump:
- dcxml
- citeproc-py-style
- invenio-search-js

EDIT: (DONE)

**Comment by krzysztof** [comment]
We need to check which other repositories will have to have those versions bumped in the dependencies

@slint already mentioned: invenio-search-js is a dependency of invenio-records-ui via it's asset bundle...
dcxml of invenio-record-rest[dublincore]

**Comment by krzysztof** [comment]
Invenio-search needs to have changes.rst updated

**Comment by krzysztof** [comment]
## First batch to review:
- [x] https://github.com/inveniosoftware/invenio-assets/pull/79
- [x] https://github.com/inveniosoftware/dcxml/pull/9 [@switowski]
- [ ] https://github.com/inveniosoftware/invenio-search-js/pull/119 [@switowski] (no release due to NPM issues)
- [x] https://github.com/inveniosoftware/invenio-cache/pull/6
- [x] https://github.com/inveniosoftware/invenio-config/pull/35
- [x] https://github.com/inveniosoftware/invenio-celery/pull/52
- [x] https://github.com/inveniosoftware/invenio-i18n/pull/68  (invenio-assets dependecy)
- [x] https://github.com/inveniosoftware/invenio-db/pull/107
- [ ] https://github.com/inveniosoftware/invenio-search/pull/135 (dependecies)
- [x] https://github.com/inveniosoftware/invenio-mail/pull/41
- [x] https://github.com/inveniosoftware/invenio-formatter/pull/57
- [x] https://github.com/inveniosoftware/invenio-logging/pull/39
- [x] https://github.com/inveniosoftware/invenio-rest/pull/88
- [x] https://github.com/inveniosoftware/citeproc-py-styles/pull/8

**Comment by krzysztof** [comment]
### Second batch:
- [x] https://github.com/inveniosoftware/invenio-base/pull/131
- [x] https://github.com/inveniosoftware/invenio-jsonschemas/pull/77
- [x] https://github.com/inveniosoftware/invenio-i18n/pull/68

**Comment by lnielsen** [comment]
Third batch:

- [x] https://github.com/inveniosoftware/invenio-app/pull/20 [@switowski]
- [x] https://github.com/inveniosoftware/invenio-accounts/pull/260
- [x] https://github.com/inveniosoftware/invenio-theme/pull/119

**Comment by krzysztof** [comment]
Fourth batch:
- [x] https://github.com/inveniosoftware/invenio-access/pull/148 (waiting for invenio-accounts PyPI release)

**Comment by lnielsen** [comment]
5th batch:
- [x] https://github.com/inveniosoftware/invenio-admin/pull/63

6th batch:
- [x] https://github.com/inveniosoftware/invenio-oauth2server/pull/176
- [x] https://github.com/inveniosoftware/invenio-userprofiles/pull/88
- [x] https://github.com/inveniosoftware/invenio-pidstore/pull/116

7th batch:

- [x] https://github.com/inveniosoftware/invenio-oauthclient/pull/169
- [x] https://github.com/inveniosoftware/invenio-records/pull/190

8th batch:
- [x] https://github.com/inveniosoftware/invenio-search/pull/135
- [x] https://github.com/inveniosoftware/invenio-records-ui/pull/80

9th batch:
- [x] https://github.com/inveniosoftware/invenio-search-ui/pull/65
- [x] https://github.com/inveniosoftware/invenio-indexer/pull/85

10th batch:
- [x] https://github.com/inveniosoftware/invenio-records-rest/pull/198

11th batch:
- [x] https://github.com/inveniosoftware/invenio-marc21/pull/63

12th batch:
- [x] https://github.com/inveniosoftware/invenio-oaiserver/pull/148
