### ISSUE TITLE
Repositories without MIT license

### ISSUE THREAD

**Issue by jorikvankemenade** [inveniosoftware/license-changer#14]
These are all the repositories in our organization that still have the GPL license.
For each repository, we created a PR that changes the GPL license to the MIT license.

### Pull requests:

- [ ] [Domapping](https://github.com/inveniosoftware/domapping) (inveniosoftware/domapping#31)
- [ ] [Deposit](https://github.com/inveniosoftware/invenio-deposit) (inveniosoftware/invenio-deposit#187)
- [ ] [OAI Havester](https://github.com/inveniosoftware/invenio-oaiharvester) (inveniosoftware/invenio-oaiharvester#54)
- [ ] [Cookiecutter Invenio](https://github.com/inveniosoftware/cookiecutter-invenio-module) (inveniosoftware/cookiecutter-invenio-module#128)
- [ ] [Metainvenio](https://github.com/inveniosoftware/metainvenio) (inveniosoftware/metainvenio#17)
- [ ] [Collections](https://github.com/inveniosoftware/invenio-collections) (inveniosoftware/invenio-collections#89)
- [ ] [Openaire](https://github.com/inveniosoftware/invenio-openaire) (inveniosoftware/invenio-openaire#58)
- [ ] [SSE](https://github.com/inveniosoftware/invenio-sse) (inveniosoftware/invenio-sse#16)
- [ ] [Github](https://github.com/inveniosoftware/invenio-github) (inveniosoftware/invenio-github#66)
- [ ] [Pages](https://github.com/inveniosoftware/invenio-pages) (inveniosoftware/invenio-pages#47)
- [ ] [CSL REST](https://github.com/inveniosoftware/invenio-csl-rest) (inveniosoftware/invenio-csl-rest#14)
- [ ] [App Demo Marc 21](https://github.com/inveniosoftware/invenio-app-demomarc21) (inveniosoftware/invenio-app-demomarc21#48)
- [ ] [Webhooks](https://github.com/inveniosoftware/invenio-webhooks)(inveniosoftware/invenio-webhooks#58)
- [ ] [Generator Invenio JS Module](https://github.com/inveniosoftware/generator-invenio-js-module) (inveniosoftware/generator-invenio-js-module#11)
- [ ] [Orcid](https://github.com/inveniosoftware/invenio-orcid) (inveniosoftware/invenio-orcid#22)
- [ ] [Communities](https://github.com/inveniosoftware/invenio-communities) (inveniosoftware/invenio-communities#122)
- [ ] [Previewer ISPY](https://github.com/inveniosoftware/invenio-previewer-ispy) (inveniosoftware/invenio-previewer-ispy#17)
- [ ] [Memento](https://github.com/inveniosoftware/invenio-memento) (inveniosoftware/invenio-memento#13)
- [ ] [Doschema](https://github.com/inveniosoftware/doschema) (inveniosoftware/doschema#15)
- [ ] [Files Processor](https://github.com/inveniosoftware/invenio-files-processor) (inveniosoftware/invenio-files-processor#10)
- [ ] [Migrator](https://github.com/inveniosoftware/invenio-migrator) (inveniosoftware/invenio-migrator#81)
- [ ] [Records JS](https://github.com/inveniosoftware/invenio-records-js) (inveniosoftware/invenio-records-js#35)
- [ ] [Charts JS](https://github.com/inveniosoftware/invenio-charts-js) (inveniosoftware/invenio-charts-js#3)
- [ ] [Queues](https://github.com/inveniosoftware/invenio-queues) (inveniosoftware/invenio-queues#7)
- [ ] [Accounts REST](https://github.com/inveniosoftware/invenio-accounts-rest) (inveniosoftware/invenio-accounts-rest#35)
- [ ] [Files JS](https://github.com/inveniosoftware/invenio-files-js) (inveniosoftware/invenio-files-js#29)

**Comment by lnielsen** [comment]
I've updated the list
